#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Install Data Dog
  hosts: Ubuntu
  sudo: True
  vars_prompt:
    - name: "dataDogKey"
      prompt: "The Data Dog API Key to use."
      private: no
      default: "4a2ad6741d78c9f690510083065a0bff"
  tasks:
    - debug: msg="dataDogKey = {{ dataDogKey }}"
    - name: Run the datadog installation script
      shell: DD_API_KEY={{ dataDogKey }} bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh)"
    - name: Add account to the docker group
      user: name=dd-agent groups=docker
    - name: Copy Docker configuration file
      copy: src=files/docker_daemon.yaml dest=/etc/dd-agent/conf.d/docker_daemon.yaml owner=dd-agent group=root mode=0444
#   - name: Copy RabbitMQ configuration file
#     copy: src=files/rabbitmq.yaml dest=/etc/dd-agent/conf.d/rabbitmq.yaml owner=dd-agent group=root mode=0444
#   - name: Copy HTTP Check configuration file
#     copy: src=files/http_check.yaml dest=/etc/dd-agent/conf.d/http_check.yaml owner=dd-agent group=root mode=0444
#   - name: Copy Redis configuration file
#     copy: src=files/redisdb.yaml dest=/etc/dd-agent/conf.d/redisdb.yaml owner=dd-agent group=root mode=0444
    - name: Restart the agent
      service: name=datadog-agent state=restarted
