#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Configure Rsyslog To Forward to Loggly
  hosts: Ubuntu
  sudo: True
  vars_prompt:
    - name: "logglyKey"
      prompt: "The Loggly API key to use."
      private: no
      default: "91ec9498-62c1-42fc-b9e9-a977628cb17d"
    - name: "logglyTag"
      prompt: "The Loggly Tag to use."
      private: no
      default: "home-server"
  tasks:
    - debug: msg="logglyKey = {{ logglyKey }}"
    - debug: msg="logglyPath = {{ logglyTag }}"
    - name: Copy Rsyslog Configuration File 
      template: src=templates/loggly.conf dest=/etc/rsyslog.d/22-loggly.conf mode=0444 backup=yes force=yes
    - name: Restart the Rsyslog
      command: /usr/sbin/service rsyslog restart
    - name: Send a test message 
      command: logger 'Hello From Ansible!'

