#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Add useful tools
  hosts: Ubuntu
  become: True
  tasks:
    - apt: "upgrade=dist state=present update_cache=true cache_valid_time=600"
    - apt: "name={{ item }} state=present update_cache=true cache_valid_time=600"
      with_items:
         - tree
         - fail2ban

- name: Add entries for local machines
  hosts: Ubuntu
  become: True
  tasks:
    - lineinfile: dest=/etc/hosts line="192.168.1.222 batcave"
    - lineinfile: dest=/etc/hosts line="192.168.1.227 stargate"
    - lineinfile: dest=/etc/hosts line="192.168.1.229 atlantis"
    - lineinfile: dest=/etc/hosts line="192.168.1.233 bifrost"
    - lineinfile: dest=/etc/hosts line="192.168.1.234 nas"
    - lineinfile: dest=/etc/hosts line="192.168.1.235 pi"
    - lineinfile: dest=/etc/hosts line="192.168.1.236 pi2"

- name: Tweak User Account
  hosts: Ubuntu
  become: False
  tasks:
    - lineinfile: dest=/home/rkurr/.bashrc line='set -o vi'

- name: Install Git
  hosts: Ubuntu
  become: True
  tasks:
    - apt: name=git state=latest update_cache=true cache_valid_time=600

- name: Configure Rsyslog To Forward to Loggly
  hosts: Ubuntu
  become: True
  vars:
      logglyKey: "91ec9498-62c1-42fc-b9e9-a977628cb17d"
      logglyTag: "basement"
  tasks:
    - template: src=templates/loggly.conf dest=/etc/rsyslog.d/22-loggly.conf mode=0444 backup=yes force=yes
    - command: /usr/sbin/service rsyslog restart
    - command: logger 'Hello From Ansible!'

- name: Install Sysdig
  hosts: Ubuntu
  become: True
  tasks:
      - apt_key: url=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public state=present
      - apt_repository: repo='deb http://download.draios.com/stable/deb stable-$(ARCH)/' state=present
      - shell: apt-get -y install linux-headers-$(uname -r)
      - apt: name=sysdig state=latest update_cache=true

- name: Mount NAS Drive
  hosts: Ubuntu
  become: True
  tasks:
      - apt: name=nfs-common state=latest update_cache=true cache_valid_time=600
      - file: path=/mnt/nas state=directory
      - mount: fstype=nfs name=/mnt/nas src=nas:/media state=mounted opts=ro

# use https://www.atlantic.net/community/howto/setup-rsync-daemon/ as guidance
- name: Install Rsync Daemon (Atlantis)
  hosts: atlantis
  become: True
  tags:
    - rsync
  tasks:
      - apt: name=rsync state=latest update_cache=true cache_valid_time=600
      - apt: name=ntfs-3g state=latest update_cache=true cache_valid_time=600
      - copy: src=files/rsyncd.conf dest=/etc/rsyncd.conf owner=root group=root mode=0444 backup=no
      - copy: src=files/rsyncd.secrets dest=/etc/rsyncd.secrets owner=root group=root mode=0600 backup=no
      # in /etc/fstab use this: UUID=5C28F67528F64D90 /mnt/backup ntfs-3g defaults,uid=1000,gid=1000,dmask=027,fmask=137,windows_names,locale=en_US.utf8 0 0 
      # after you change the password, run rsync --daemon

- name: Mount NAS Drive (Atlantis)
  hosts: atlantis
  become: True
  tasks:
      - apt: name=nfs-common state=latest update_cache=true cache_valid_time=600
      - file: path=/mnt/plex-configuration state=directory
      - mount: fstype=nfs name=/mnt/plex-configuration src=nas:/atlantis-pc state=mounted opts=rw
      - file: path=/mnt/torrent-sync state=directory
      - mount: fstype=nfs name=/mnt/torrent-sync src=nas:/atlantis-sync state=mounted opts=rw
      - file: path=/mnt/torrent-book state=directory
      - mount: fstype=nfs name=/mnt/torrent-book src=nas:/atlantis-book state=mounted opts=rw
      - file: path=/mnt/artifactory/data state=directory
      - mount: fstype=nfs name=/mnt/artifactory/data src=nas:/atlantis-jfrog-data state=mounted opts=rw
      - file: path=/mnt/artifactory/etc state=directory
      - mount: fstype=nfs name=/mnt/artifactory/etc src=nas:/atlantis-jfrog-etc state=mounted opts=rw
      - file: path=/mnt/consul state=directory
      - mount: fstype=nfs name=/mnt/consul src=nas:/atlantis-consul state=mounted opts=rw
      - file: path=/mnt/elasticsearch state=directory
      - mount: fstype=nfs name=/mnt/elasticsearch src=nas:/atlantis-search state=mounted opts=rw

- name: Mount NAS Drive (Stargate)
  hosts: stargate
  become: True
  tasks:
      - apt: name=nfs-common state=latest update_cache=true cache_valid_time=600
      - file: path=/mnt/plex-configuration state=directory
      - mount: fstype=nfs name=/mnt/plex-configuration src=nas:/stargate-pc state=mounted opts=rw
      - file: path=/mnt/torrent-sync state=directory
      - mount: fstype=nfs name=/mnt/torrent-sync src=nas:/atlantis-sync state=mounted opts=ro
      - file: path=/mnt/owncloud state=directory
      - mount: fstype=nfs name=/mnt/owncloud src=nas:/stargate-own state=mounted opts=rw
      - file: path=/mnt/mysql state=directory
      - mount: fstype=nfs name=/mnt/mysql src=nas:/stargate-mysql state=mounted opts=rw
      - file: path=/mnt/consul state=directory
      - mount: fstype=nfs name=/mnt/consul src=nas:/stargate-consul state=mounted opts=rw

- name: Mount NAS Drive (Bifrost)
  hosts: bifrost
  become: True
  tasks:
      - apt: name=nfs-common state=latest update_cache=true cache_valid_time=600
      - file: path=/mnt/plex-configuration state=directory
      - mount: fstype=nfs name=/mnt/plex-configuration src=nas:/bifrost-pc state=mounted opts=rw
      - file: path=/mnt/torrent-sync state=directory
      - mount: fstype=nfs name=/mnt/torrent-sync src=nas:/atlantis-sync state=mounted opts=ro
      - file: path=/mnt/consul state=directory
      - mount: fstype=nfs name=/mnt/consul src=nas:/bifrost-consul state=mounted opts=rw

- name: Install Docker
  hosts: nobody
  become: True
  tasks:
    - apt: name=curl state=latest update_cache=true cache_valid_time=600
    - command: /usr/bin/curl --location --output /root/install-docker https://get.docker.com/
    - file: path=/root/install-docker owner=root group=root mode=0500
    - shell: /root/install-docker
    - file: path=/etc/systemd/system/docker.service.d state=directory mode=0755
    - copy: src=files/root-dir.conf dest=/etc/systemd/system/docker.service.d/root-dir.conf owner=root group=root mode=444 backup=no
    - command: usermod -aG docker rkurr
    - command: systemctl daemon-reload
    - command: systemctl restart docker
    - command: docker run hello-world

    - shell: /usr/bin/curl --location --output /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m`
    - file: path=/usr/local/bin/docker-compose owner=root group=root mode=0555
    - command: docker-compose --version

    - get_url: url=https://github.com/docker/machine/releases/download/v0.7.0/docker-machine-Linux-x86_64 dest=/usr/local/bin/docker-machine mode=0555
    - command: docker-machine --version

- name: Install Compose Scripts (Atlantis)
  hosts: atlantis
  become: False
  tags:
    - compose
  tasks:
    - file: path=/home/rkurr/docker-compose state=directory mode=0755
    - copy: src=files/docker-compose-atlantis.yml dest=/home/rkurr/docker-compose/docker-compose.yml owner=rkurr group=rkurr mode=444 backup=no
    - file: path=/home/rkurr/docker-compose/consul state=directory mode=0755
    - copy: src=files/consul-atlantis.json dest=/home/rkurr/docker-compose/consul/atlantis.json owner=rkurr group=rkurr mode=444 backup=no
    - file: path=/home/rkurr/docker-compose/logstash state=directory mode=0755
    - copy: src=files/logstash-atlantis.conf dest=/home/rkurr/docker-compose/logstash/logstash.conf owner=rkurr group=rkurr mode=444 backup=no

- name: Install Compose Scripts (Stargate)
  hosts: stargate
  become: False
  tags:
    - compose
  tasks:
    - file: path=/home/rkurr/docker-compose state=directory mode=0755
    - copy: src=files/docker-compose-stargate.yml dest=/home/rkurr/docker-compose/docker-compose.yml owner=rkurr group=rkurr mode=444 backup=no
    - file: path=/home/rkurr/docker-compose/consul state=directory mode=0755
    - copy: src=files/consul-stargate.json dest=/home/rkurr/docker-compose/consul/stargate.json owner=rkurr group=rkurr mode=444 backup=no

- name: Install Compose Scripts (Bifrost)
  hosts: bifrost
  become: False
  tags:
    - compose
  tasks:
    - file: path=/home/rkurr/docker-compose state=directory mode=0755
    - copy: src=files/docker-compose-bifrost.yml dest=/home/rkurr/docker-compose/docker-compose.yml owner=rkurr group=rkurr mode=444 backup=no
    - file: path=/home/rkurr/docker-compose/consul state=directory mode=0755
    - copy: src=files/consul-bifrost.json dest=/home/rkurr/docker-compose/consul/bifrost.json owner=rkurr group=rkurr mode=444 backup=no

