# Atlantis 
version: '2'
services:
    torrent-sync:
        image: kurron/docker-bittorrent-sync:latest
        container_name: torrent-sync
        restart: always
        network_mode: host
        volumes:
        - /mnt/torrent-book:/mnt/bookkeeping
        - /mnt/torrent-sync:/mnt/sync
