# Atlantis 
version: '2'
services:
    torrent-sync:
        image: kurron/docker-bittorrent-sync:latest
        container_name: torrent-sync
        restart: always
        network_mode: host
        volumes:
        - /mnt/torrent-book:/mnt/bookkeeping
        - /mnt/torrent-sync:/mnt/sync
    data-dog:
        image:  datadog/docker-dd-agent:latest
        container_name: data-dog
        restart: always
        network_mode: "host"
        environment:
            API_KEY: 4a2ad6741d78c9f690510083065a0bff
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    plex:
        image: timhaak/plex:latest
        container_name: plex
        restart: always
        network_mode: host
        volumes:
        - /mnt/plex-configuration:/config
        - /mnt/nas:/mnt/media:ro
        - /mnt/torrent-sync:/mnt/torrent:ro
        environment:
            SKIP_CHOWN_CONFIG: "TRUE"
    artifactory-data:
        image: busybox:latest
        container_name: artifactory-data
        network_mode: none
        command: "true"
        volumes:
        - /var/opt/jfrog/artifactory/logs
        - /var/opt/jfrog/artifactory/backup
    artifactory:
        image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:latest
        container_name: artifactory
        restart: always
        network_mode: host
        volumes_from:
        - artifactory-data:rw
        volumes:
        - /mnt/artifactory/etc:/var/opt/jfrog/artifactory/etc:rw
        - /mnt/artifactory/data:/var/opt/jfrog/artifactory/data:rw
        environment:
        - ARTIFACTORY_HOME=/var/opt/jfrog/artifactory
    consul:
        image: consul:latest
        container_name: consul
        restart: always
        network_mode: host
        volumes:
        - ./consul:/consul/config:ro
        - /mnt/consul:/consul/data:rw
        command: consul agent -config-dir /consul/config
    elasticsearch:
        image: elasticsearch:latest
        container_name: elasticsearch
        restart: always
        network_mode: host
        volumes:
        - /mnt/elasticsearch:/usr/share/elasticsearch/data:rw
        command:  elasticsearch -Des.node.name="Basement"
    kibana:
        image: kibana:latest
        container_name: kibana
        restart: always
        network_mode: host
        environment:
            ELASTICSEARCH_URL: http://192.168.1.229:9200
    logstash:
        image: logstash:latest
        container_name: logstash
        restart: always
        network_mode: host
        volumes:
        - ./logstash:/config:ro
        command: logstash -f /config/logstash.conf
    configuration-server:
        image: kurron/docker-spring-cloud-configuration-server:1.1.0
        container_name: configuration-server
        restart: always
        network_mode: host
        environment:
            SPRING_CLOUD_CONSUL_HOST: 192.168.1.229
