# Stargate 
version: '2'
services:
    plex:
        image: timhaak/plex:latest
        container_name: plex
        restart: always
        network_mode: host
        volumes:
        - /mnt/plex-configuration:/config
        - /mnt/nas:/mnt/media:ro
        - /mnt/torrent-sync:/mnt/torrent:ro
        environment:
            SKIP_CHOWN_CONFIG: "TRUE"

    data-dog:
        image:  datadog/docker-dd-agent:latest
        container_name: data-dog
        restart: always
        network_mode: "host"
        environment:
            API_KEY: 4a2ad6741d78c9f690510083065a0bff
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

    mysql:
        image: mysql:latest
        container_name: mysql
        network_mode: host
        restart: always
        volumes:
        - /mnt/mysql:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: sa
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_DATABASE: owncloud

    owncloud:
        image: owncloud:latest
        container_name: owncloud
        restart: always
        network_mode: host
        volumes:
        - /mnt/owncloud:/var/www/html:rw
        - /mnt/nas:/mnt/media:ro
        - /mnt/torrent-sync:/mnt/torrent:ro
        depends_on:
        - mysql

    consul:
        image: consul:latest
        container_name: consul
        restart: always
        network_mode: host
        volumes:
        - ./consul:/consul/config:ro
        - /mnt/consul:/consul/data:rw

    configuration-server:
        image: kurron/docker-spring-cloud-configuration-server:1.3.1
        container_name: configuration-server
        restart: always
        network_mode: host
        environment:
            SPRING_CLOUD_CONSUL_HOST: 192.168.1.227
            JVM_HEAP_MIN: "128m"
            JVM_HEAP_MAX: "128m"
            JVM_JMX_PORT: "8020"
            JVM_JMX_RMI_PORT: "8020"
            JVM_JMX_HOST: "192.168.1.227"
            SERVER_PORT: "8080"

